### ISSUE TITLE
Extended GCD of polynomials

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/poly#22]
- [x] Extended GCD of dense polynomials.
- [x] Extended GCD of sparse polynomials.
- [x] Benchmark extended GCD on binary polynomials.
- [ ] Efficient implementation of extended GCD for dense polynomials, using mutable vectors.

**Comment by Bodigrim** [comment]
@Multramate are you interested to pick up remaining tasks?

**Comment by Multramate** [comment]
I will be doing this for sparse polynomials, but I don't know enough about the effect of mutability on performance to make the algorithms actually efficient, and I've mentioned that the benchmarks seem to show that `gcdExt` is quite fast.

On a side note, it seems that `fractionalGcd` in `Internal/Sparse/Fractional.hs` isn't actually being used?

**Comment by Bodigrim** [comment]
Cool! I'll take a closer look on performance of `gcdExt` later. 

> On a side note, it seems that fractionalGcd in Internal/Sparse/Fractional.hs isn't actually being used?

Good catch, I will remove it. The thing is that there is no point in pursuing an effective implementation of `gcd` for sparse polynomials. While addition and multiplication preserves "sparseness", division does not and intermediate computations of `gcd` inevitable become boggled in myriads of non-zero coefficients. For any serious applications (not just playing in REPL) one should switch to dense polynomials, compute gcd and get back to sparse.

**Comment by Multramate** [comment]
Thank you!

**Comment by Multramate** [comment]
Great! Would you spare some time to investigate the performance of the unexpectedly fast (in terms of benchmarks) dense `gcdExt` functions?

**Comment by Bodigrim** [comment]
I would like dense `gcdExt` not to allocate anything during recursive calls. This is how `fieldGcd` works: it allocates two buffers for `gcdM` once, but neither `gcdM` nor `remainderM` allocate a thing. It is important to lift pressure from garbage collector whenever possible.

Sorry, I have not yet got time to look thoroughly on benchmerks.

**Comment by Bodigrim** [comment]
I took a look at benchmarks in `DenseBench`.

```haskell
doGcdExt :: Int -> Rational
doGcdFrac :: Int -> Rational
```

AFAIU you observe that `doGcdExt` and `doGcdFrac` take almost the same time, which could imply that `gcdExt` is fast enough. 

The problem here is that `Rational` coefficients in intermediate computations grow so rapidly that instead of `gcdFrac` / `gcdExt` we benchmark multiplication of long integers. 

It would be more representative to use not `Rational, but a `Field` with O(1) division (e. g., `Bool`, giving us binary polynomials). Such benchmarks would allow us to make an informed decision on performance of `gcdExt` itself.

**Comment by Bodigrim** [comment]
It appeared that you were right :) I've written benchmarks for `gcdExt` over binary polynomials, but even for this simplest field `gcdExt` is not significantly slower than `gcdFrac`. 

Thanks for your excellent contributions!

**Comment by Multramate** [comment]
Thank you - sorry for not being able to implement the benchmarks as I have been busy.

Can this be released as a new version anytime soon? There are a few libraries from our side that depend on `gcdExt` indirectly.

**Comment by Bodigrim** [comment]
Done: http://hackage.haskell.org/package/poly-0.3.2.0
