### ISSUE TITLE
Support Laurent polynomials

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/poly#23]

**Comment by Multramate** [comment]
Currently working on this on a fork. I can think of two ways of approaching this:
- By mimicking the `Dense` polynomials, as `(Int, v a)` rather than `v a`, where the first integer records the minimum polynomial degree.
- By mimicking the `Sparse` polynomials as ` v (Int, a)` rather than `v (Word, a)`, which records negative exponents. This has already been tested and benchmarked in the fork and it works.

On a side note, doing `scale` with negative integers and other related functions on `Dense` polynomials lead to non-termination - would be nice if this is caught explicitly :)

**Comment by Bodigrim** [comment]
I would like to mitigate somehow the combinatorial explosion of different flavors of polynomials, both in API and in implementation. Changing representation of sparse polynomials from `Vector (Word, a)` to `Vector (Int, a)` is tempting, but offers little code sharing and cannot be applied to dense polynomials. On the other hand, `data Laurent v a = Laurent !Int !(v a)` is applicable to both flavors and can be implemented as a thin layer over normal polynomials. So I would follow the latter avenue.

I believe it is enough to provide only `Semiring`-based interface for Laurent polynomials.

Main differences are:

* `eval` for Laurent polynomials requires `Fractional` constraint.
* `integral` is impossible to implement (because of `integral (X^(-1))`).
* `Euclidean` is impossible to implement (because division with remainder is undefined).

**Comment by Multramate** [comment]
In the latter data type, if by `Laurent n [a,b,c]` you mean `aX^-n + bX^-(n-1) + cX^-(n-2)`, then I don't quite see how it would also be applicable to sparse polynomials. The one I have already implemented seems more intuitive and convenient to reason/use in our other libraries, despite the lack of code sharing.

**Comment by Bodigrim** [comment]
Sorry, my bad. I meant `data Laurent v a = Laurent !Int !(Poly v a)` with implementation, piggy-backing on normal polynomials.

```haskell
instance Num (Laurent v a) where 
  Laurent n1 xs1 * Laurent n2 xs2 = Laurent (n1 + n2) (xs1 * xs2)
  Laurent n1 xs1 + Laurent n2 xs2 
    | n1 <= n2  = Laurent n1 (xs1 + scale (n2 - n1) one xs2)
    | otherwise = Laurent n2 (scale (n1 - n2) one xs1 + xs2)
```

One would still need to write `Laurent` for dense and for sparse polynomials, but implementations look to be very concise and matching up to constraints (`Vector v a` vs. `Vector (Word, a)`).

**Comment by Bodigrim** [comment]
I suggest module names `Data.Poly.Laurent` and `Data.Poly.Sparse.Laurent`, both implementing `Semiring`-based interfaces.

**Comment by Multramate** [comment]
Sounds good - will follow this convention when I have the time to continue implementing these.

**Comment by Bodigrim** [comment]
@Multramate any plans to work on this issue? I can possibly pick it up myself, if you are busy these days. Not a pressing issue, but I'd like to deliver it by Christmas.

**Comment by Acentelles** [comment]
Hi @Bodigrim I have some bandwidth to work on this issue

**Comment by Multramate** [comment]
Thanks @Acentelles !

**Comment by Bodigrim** [comment]
@Acentelles feel free to ping me if you need any help with this.

**Comment by Acentelles** [comment]
Hi @Bodigrim, I wish I had worked more on this issue. I've just opened a work-in-progress PR. I'm quite saturated with work at the moment, but I plan to have more time again from the second half of February.

**Comment by Bodigrim** [comment]
@Acentelles I am fine with this timeline, thanks for your contribution. No worries, I know myself that a full-time job leaves little space for open source. 

On the other hand, if you are still busy by the end of February, I'll probably assign this task to myself.

**Comment by Bodigrim** [comment]
@Acentelles any chance to pick it up again soon?

**Comment by Bodigrim** [comment]
OK, I'll take a stab myself.
