### ISSUE TITLE
test/Dense.hs:251:54: error: Not in scope: ‘S.integral’

### ISSUE THREAD

**Issue by juhp** [Bodigrim/poly#32]
For Stackage LTS 14:

```
    Building test suite 'poly-tests' for poly-0.3.2.0..
    [2 of 4] Compiling Dense
    
    /var/stackage/work/unpack-dir/unpacked/poly-0.3.2.0-0a08b17044344cfa9923aefddad623987d12ed2d25738f5acb46f2ec71f8610d/test/Den
se.hs:251:54: error:
        Not in scope: ‘S.integral’
        Module ‘Data.Poly.Semiring’ does not export ‘integral’.
        |
    251 |     \(p :: Poly V.Vector Rational) -> integral p === S.integral p
        |                                                      ^^^^^^^^^^
```

**Comment by Bodigrim** [comment]
Thanks. Fixed in `master`, but I am reluctant to roll out a release for this. Could you please disable tests in Stackage?

**Comment by juhp** [comment]
https://www.stackage.org/lts-14.8/package/poly-0.3.1.0

**Comment by Bodigrim** [comment]
Fixed in `poly-0.3.3.0`.

**Comment by juhp** [comment]
Unless you want the tests re-enabled in LTS, I think you can close this now, otherwise please [open a ticket](https://github.com/commercialhaskell/lts-haskell/issues).

**Comment by Bodigrim** [comment]
Disabled tests are fine. Is anything blocking `poly-0.3.3.0` from an upcoming `lts-14.*`?
