### ISSUE TITLE
Reuse Data.Euclidean.gcdExt

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/poly#38]
I would like to reuse `gcdExt` from `semirings` somehow. There are two possible avenues:

1. Decomission `Data.Poly.gcdExt` and `Data.Poly.Sparse.gcdExt` entirely. This seems to be the cleanest solution in the long run, but it has a drawback: `Data.Euclidean.gcdExt` does not normalize polynomials as `scaleMonic` does. A client could possibly normalize the output on his side (if he actually cares about having it normalized).

2. Reuse `Data.Euclidean.gcdExt` in `Data.Poly.gcdExt` and `Data.Poly.Sparse.gcdExt`, but still apply `scaleMonic` and leave both entities exported. This is backwards compatible, but kinda annoying: anyone importing `Data.Euclidean` and `Data.Poly` together would need to hide either of `gcdExt`, leading to an awfully huge chance to use the wrong one (because on many inputs they return the same values). 

At the moment I am more inclined to follow the first option. 

@Multramate what do you think about it? Would it be difficult to normalize polynomials in `galois-field`?

**Comment by Multramate** [comment]
The first option makes more sense to me as well.

It shouldn't be difficult to normalise the outputs in `galois-field`, so that's not a problem.

**Comment by Bodigrim** [comment]
Good. I have implemented the first option.
