### ISSUE TITLE
definition of `degree` in Data.Poly.Internal.Dense.Field is nonstandard

### ISSUE THREAD

**Issue by davidsd** [Bodigrim/poly#43]
The module `Data.Poly.Internal.Dense.Field` defines `degree` as

      degree (Poly xs) = fromIntegral (G.length xs)

For example, `degree X = 2` and `degree 1 = 1`. This is not the standard definition of polynomial degree, which has `degree_standard X = 1` and `degree_standard 1 = 0` and could cause confusion. Is there a reason it is implemented this way?

**Comment by Bodigrim** [comment]
What would be `degree_standard 0`?

**Comment by davidsd** [comment]
Good question. As far as I know, there is no universal agreed-upon answer for that. Some people define `degree 0 = 0`, some define `degree = -1`, and some define `degree = -infinity`. In my code, I generally use `degree 0 = 0`. Given that type of `degree` in `Euclidean` is `a -> Natural`, that seems to be the only option available. Would it break things to have `degree 0 == degree 1`?

**Comment by Bodigrim** [comment]
I thought that it will, but I just gave it a try and all tests are passing. It totally make sense to switch to the standard definition, thanks for noticing it.

**Comment by davidsd** [comment]
Awesome -- thanks!
