### ISSUE TITLE
Euclidean methods are unergonomic with Fractional

### ISSUE THREAD

**Issue by davidsd** [Bodigrim/poly#44]
Perhaps I'm doing things wrong, but in order to implement `quotRem` for my `newtype` over `VPoly a`, I had to do the following

```haskell
coercePoly :: (Eq b, Num b) => Coercible a b => Poly.VPoly a -> Poly.VPoly b
coercePoly = Poly.toPoly . coerce . Poly.unPoly

quotRem :: forall a . (Eq a, Fractional a) => Polynomial a -> Polynomial a -> (Polynomial a, Polynomial a)
quotRem (Polynomial p1) (Polynomial p2) = (Polynomial (coercePoly q), Polynomial (coercePoly r))
  where
    (q,r) = Euclidean.quotRem p1' p2'
    p1' :: Poly.VPoly (Euclidean.WrappedFractional a) = coercePoly p1
    p2' :: Poly.VPoly (Euclidean.WrappedFractional a) = coercePoly p2
```

There are two issues: firstly, the need to use `WrappedFractional` is a little cumbersome. It would be a bit easier if something like `coercePoly` were included, or better if there were an instance `Fractional a => Euclidean (VPoly a)`. The other issue is that `coercePoly` requires using `toPoly`, which includes extra constraints and traverses the coefficients. It would be nice if there were an unsafe way to map over the coefficients, which could be used when the user knows the mapping function will never take nonzero values to zero values.

**Comment by davidsd** [comment]
By the way, an unsafe map over coefficients would also be useful in parsing code where wrapping and unwrapping newtypes is common.

**Comment by Bodigrim** [comment]
The problem is that `Coercible a b` does not guarantee that `coerce (zero :: a) == (zero :: b)`. And if it holds, `toPoly` will take only O(1) time: if the last coefficient is non-zero, it will not traverse coefficients any further. So `coercePoly` altogether is O(1), which looks OK from my viewpoint.

I agree that wrapping-unwrapping `WrappedFractional` is cumbersome. Unfortunately, GHC does not allow to have both `Fractional a => Euclidean (VPoly a)` and `Field a => Euclidean (VPoly a)` at the same time. Not sure what is the best way to cut the boilerplate here.

**Comment by davidsd** [comment]
Ah, that's nice about `toPoly` being O(1). I should have realized that.

**Comment by Bodigrim** [comment]
Here is my solution (a bit code-golfish):

```haskell
{-# LANGUAGE FlexibleContexts    #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications    #-}

import Control.Arrow 
import Data.Coerce
import qualified Data.Euclidean as E
import Data.Function 
import Data.Poly (VPoly, toPoly, unPoly)
import Data.Vector (Vector)

newtype Polynomial a = Polynomial { unPolynomial :: VPoly a }

coercePoly :: (Coercible a b, Eq a, Num a, Eq b, Num b, Coercible u (VPoly a), Coercible v (VPoly b)) => u -> v  
coercePoly = coerce (toPoly @_ @Vector . coerce . unPoly @Vector)

quotRem :: forall a. (Eq a, Fractional a) => Polynomial a -> Polynomial a -> (Polynomial a, Polynomial a)
quotRem = ((coercePoly *** coercePoly) .) . (E.quotRem @(VPoly (E.WrappedFractional a)) `on` coercePoly) 
```

**Comment by davidsd** [comment]
Thanks, there are some useful elements in this solution.

**Comment by Bodigrim** [comment]
I've added a wrapper `quotRemFractional`, providing `quotRem` functionality for polynomials with `Fractional` coefficients.

**Comment by davidsd** [comment]
Awesome! Thanks!
