### ISSUE TITLE
Add a definition for the identity polynomial

### ISSUE THREAD

**Issue by Jashweii** [Bodigrim/poly#5]
Add a definition for the identity polynomial.
```Haskell
var :: Num a => Poly a
var = Poly [0, 1]
```
Allows writing e.g. ``3*var^2 + 5*var + 2``. If other univariate polynomial types are added (e.g. the other issues) this could be a class. It could also be used to fold polynomial types. (I'll make another issue for this, evaluation is one example.)
It might be possible to use pattern synonyms to have a concise name that isn't likely to conflict with other variables. Though this generates an extra Eq constraint (and can be used to pattern match):
```Haskell
pattern X = Poly [0, 1]
-- 3*X^2 + 5*X + 2 
-- :: (Eq a, Num a) => Poly a
```

**Comment by Bodigrim** [comment]
Yep, this is very useful. We cannot go for a pattern synonym, because internally `Poly` uses a vector and we cannot pattern-match on them. I've added `var` and `var'` in d6aa57d, however I am still not confident about naming.

**Comment by Jashweii** [comment]
I agree about the naming being unfortunate. It should be possible to use ViewPatterns in a pattern synonym:
```Haskell
-- X1/X2 are different implementations of the same thing
pattern X1 <- ((==) var -> True)
  where X1 = var
pattern X2 = Poly (VecList [0, 1])

-- more generally if any other patterns are needed
pattern VecList :: [a] -> Data.Vector.Vector a
pattern VecList xs <- (Data.Vector.toList -> xs)
  where VecList xs  =  Data.Vector.fromList xs
```

**Comment by Bodigrim** [comment]
Done, thanks for help with pattern synonyms.
