### ISSUE TITLE
Folding or evaluating polynomials

### ISSUE THREAD

**Issue by Jashweii** [Bodigrim/poly#6]
```Haskell
foldP  :: Num a      => Poly a -> a -> a
foldP' :: Semiring a => Poly a -> a -> a
-- pseudo code
foldP f(x) v = f(v)
foldP (a + bx + cx^2 + ...) v = a + b v + c v^2 + ...
-- if there is some other type of polynomial we can fold into it, where v above would be v(X) = X
-- I think this can be used to compose polynomials also
```
(Strict variants?) It should be possible to have x^n as part of the accumulator so at each step it's only one addition and one multiplication. 
I thought about ``foldMapP :: Num r => (a -> r) -> Poly a -> r -> r`` but it won't necessarily preserve the meaning of the polynomial, e.g. ``foldP p a + foldP q a == foldP (p + q) a``. (Similarly for other ring operations *I believe*.) I'm not too well versed but I think the input function would need to be a "ring homomorphism".

**Comment by Bodigrim** [comment]
Good idea. It is very interesting that due to overloading we can express both evaluation and composition of polynomials as a one function, like `eval (var^3) (var + 1)`.

I made a draft e8ea493, which awaits to be tested and documented. And maybe switch to a strict pair.

**Comment by Bodigrim** [comment]
Switched to a strict pair.
